site_name: CraftStudio API
pages: 
  - Home: 'index.md'
  - Installation: 'add-api-project.md'
  - Javadoc: 'javadoc.md'
  - Example Mod: 'exemple-mod.md'
  - CrafStudio Software:
    - Exportation: 'export-cs.md'
  

theme: default
#theme_dir: 'craftstudio_theme'
