site_name: CraftStudio API
pages: 
  - Home: 'index.md'
  - Installation: 'add-api-project.md'
  - CrafStudio Software:
    - Exportation: 'export-cs.md'
  

theme: null
theme_dir: 'craftstudio_theme'
